# Generated by Django 4.2.30 on 2026-05-18 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(validators=[profiles.models.validate_age])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1)),
                ('ethnicity', models.CharField(max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('sect', models.CharField(choices=[('SU', 'Sunni'), ('SH', 'Shia'), ('OT', 'Other'), ('PN', 'Prefer not to say')], db_index=True, max_length=2)),
                ('religiosity_level', models.IntegerField(choices=[(1, 'Cultural'), (2, 'Practicing sometimes'), (3, 'Practicing'), (4, 'Devout'), (5, 'Scholar')], db_index=True)),
                ('marital_status', models.CharField(choices=[('SI', 'Single'), ('DI', 'Divorced'), ('WI', 'Widowed')], db_index=True, max_length=2)),
                ('has_children', models.BooleanField(default=False)),
                ('wants_children', models.BooleanField(default=True)),
                ('education', models.CharField(choices=[('SE', 'Secondary'), ('VT', 'Vocational Training or Learned a Trade'), ('HD', 'High-School Diploma'), ('BA', 'Bachelors'), ('MA', 'Masters'), ('PHD', 'Doctorate'), ('OT', 'Other')], max_length=3)),
                ('occupation', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('wali_preference', models.BooleanField(default=False)),
                ('profile_visibility', models.CharField(choices=[('PU', 'Public'), ('SB', 'Subscribers only'), ('HI', 'Hidden')], db_index=True, default='PU', max_length=2)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
