# Generated by Django 4.2.30 on 2026-05-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('SI', 'Single'), ('DI', 'Divorced'), ('WI', 'Widowed'), ('MR', 'Married')], db_index=True, max_length=2),
        ),
    ]
