# Generated by Django 4.2.30 on 2026-05-25 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_alter_profile_marital_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_given', to='profiles.profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_received', to='profiles.profile')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('from_profile', 'to_profile')},
            },
        ),
    ]
